class EnguinsDropdown {
  List<String> enginDropdown = [
    "Ambulance",
    "Auto-tamponneuse",
    "Camionnette",
    "Camping-car",
    "Cyclecar",
    "Dépanneuse",
    "Tricar",
    "Véhicule",
    "Pick Up",
    "SUV",
    "Véhicule de liaison",
    "Voiture à moteur de moto",
    "Voiture solaire",
    "Voiturette de golf",
    "Chargeuse compacte",
    "Mini Pelle",
    "Chargeuses pneus",
    "Chargeuses pelleteuse",
    "Finisseur",
    "Machine à coffrage glissant", 
    "Répandeur de chaux", 
    "Gravillonneur auto-moteur", 
    "Pulvimixeur", 
    "Fraiseuse",
    "Niveleuse ",
    "Compacteur",
    "Rouleaux duplex",
    "Rouleaux monobille", 
    "Dumper", 
    "Tombereaux",
    "Décapeuse automotrice"
  ];
}
